const menu = {
	// 模块化加命名空间
    list() {
        return [
   
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"资料信息管理",
	                    "menuJump":"列表",
	                    "tableName":"kecheng"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "修改"
	                    ],
	                    "menu":"资料信息留言管理",
	                    "menuJump":"列表",
	                    "tableName":"kechengLiuyan"
	                }
	            ],
	            "menu":"资料信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"题集管理",
	                    "menuJump":"列表",
	                    "tableName":"exampaper"
	                }
	            ],
	            "menu":"题集管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"习题管理",
	                    "menuJump":"列表",
	                    "tableName":"examquestion"
	                }
	            ],
	            "menu":"习题管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"学生做题记录",
	                    "menuJump":"列表",
	                    "tableName":"examrecord"
	                }
	            ],
	            "menu":"做题记录"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"教师",
	    "tableName":"jiaoshi"
	}
	,{
	    "backMenu":[
	        {
	            "child":[
                    {
	                    "buttons":[
                            "查看",
                            "做题"
	                    ],
	                    "menu":"题集管理",
	                    "menuJump":"列表",
	                    "tableName":"exampaper"
	                },
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"做题记录",
	                    "menuJump":"列表",
	                    "tableName":"examrecord"
	                },
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"错题本",
	                    "menuJump":"列表",
	                    "tableName":"examrewrongquestion"
	                }
	            ],
	            "menu":"做题管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"资料信息管理",
			            "menuJump":"列表",
			            "tableName":"kecheng"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "修改"
			            ],
			            "menu":"资料信息留言详情",
			            "menuJump":"列表",
			            "tableName":"kechengLiuyan"
			        }
			    ],
			    "menu":"资料信息管理"
			}
	    ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"学生",
        "tableName":"yonghu"
	}
]
    }
}
export default menu;
